In [1]:
%load_ext autoreload
%autoreload 2

from core.GraphCreator import GraphCreator
from core.PropagationAlgorithm import Propagation

# Setup

In [2]:
gc = GraphCreator("items.txt", "recipes.json")

INFO - GraphCreator - _generateGraph - Generating Graph
INFO - GraphCreator - _generateGraph - Added 5390 item nodes
ERROR - GraphCreator - _generateGraph - No output for create:mixing/honey
ERROR - GraphCreator - _generateGraph - No output for create:mixing/lava_from_cobble
ERROR - GraphCreator - _generateGraph - No output for create:mixing/chocolate_melting
ERROR - GraphCreator - _generateGraph - No output for create:mixing/tea
ERROR - GraphCreator - _generateGraph - No output for create:mixing/chocolate
ERROR - GraphCreator - _generateGraph - No output for create:mixing/chocolate
INFO - GraphCreator - _generateGraph - Added 1749 ingredient nodes
INFO - GraphCreator - _generateGraph - Added 6281 recipe nodes
INFO - GraphCreator - __init__ - Full graph with following info : DiGraph with 13420 nodes and 19912 edges
INFO - GraphCreator - _collapseCycles - Condensing cycles
INFO - GraphCreator - _getCycles - Found 236 cycles
INFO - GraphCreator - _collapseCycles - Found 2844 nodes within cycles
INFO - GraphCreator - __init__ - Directed Acyclical Graph with following info : DiGraph with 10812 nodes and 15151 edges

In [3]:
prop = Propagation(gc.G)
prop.generateAtomicInputs()

INFO - Propagation - generateAtomicInputs - Getting atomic inputs
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-190 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-192 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-193 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-198 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-209 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-211 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-214 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-216 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-217 with 63 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-221 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-222 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-226 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-229 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-231 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-233 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-234 with 6 nodes
WARNING - Propagation - generateAtomicInputs - Cycle detected: cycle-235 with 6 nodes
INFO - Propagation - _filterAtomicInputs - Banned keywords are : {'minecraft:*spawner', 'minecraft:end_portal_frame', 'minecraft:chorus_plant', '*creative*', 'minecraft:light', '*spawn_egg', 'minecraft:budding_amethyst', '*:infested_*', 'minecraft:structure*', 'minecraft:farmland', 'minecraft:reinforced_deepslate', 'minecraft:jigsaw', '*debug_*', 'minecraft:dirt_path', 'create:minecart_contraption', 'minecraft:petrified_oak_slab', '*command_block*', 'minecraft:knowledge_book', 'minecraft:bedrock', 'minecraft:barrier'}
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:*spawner matches with ['minecraft:spawner', 'minecraft:trial_spawner']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:end_portal_frame matches with ['minecraft:end_portal_frame']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:chorus_plant matches with ['minecraft:chorus_plant']
DEBUG - Propagation - _filterAtomicInputs - Keyword *creative* matches with ['create:creative_motor', 'create:creative_crate', 'create:creative_fluid_tank', 'create:creative_blaze_cake']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:light matches with ['minecraft:light']
DEBUG - Propagation - _filterAtomicInputs - Keyword *spawn_egg matches with ['mowziesmobs:umvuthana_crane_spawn_egg', 'palegarden:creaking_spawn_egg', 'minecraft:shulker_spawn_egg', 'irons_spellbooks:priest_spawn_egg', 'minecraft:zombie_spawn_egg', 'minecraft:iron_golem_spawn_egg', 'minecraft:enderman_spawn_egg', 'minecraft:creeper_spawn_egg', 'minecraft:wither_skeleton_spawn_egg', 'minecraft:rabbit_spawn_egg', 'irons_spellbooks:dead_king_corpse_spawn_egg', 'minecraft:stray_spawn_egg', 'minecraft:sniffer_spawn_egg', 'mowziesmobs:bluff_spawn_egg', 'minecraft:wolf_spawn_egg', 'minecraft:husk_spawn_egg', 'minecraft:wither_spawn_egg', 'mowziesmobs:wroughtnaut_spawn_egg', 'minecraft:strider_spawn_egg', 'palegarden:creaking_heart_spawn_egg', 'minecraft:slime_spawn_egg', 'minecraft:camel_spawn_egg', 'minecraft:tadpole_spawn_egg', 'minecraft:cow_spawn_egg', 'minecraft:cod_spawn_egg', 'minecraft:villager_spawn_egg', 'minecraft:skeleton_spawn_egg', 'minecraft:goat_spawn_egg', 'minecraft:elder_guardian_spawn_egg', 'minecraft:bee_spawn_egg', 'minecraft:snow_golem_spawn_egg', 'minecraft:ravager_spawn_egg', 'minecraft:sheep_spawn_egg', 'minecraft:ender_dragon_spawn_egg', 'minecraft:chicken_spawn_egg', 'minecraft:glow_squid_spawn_egg', 'mowziesmobs:umvuthana_spawn_egg', 'irons_spellbooks:necromancer_spawn_egg', 'irons_spellbooks:apothecarist_spawn_egg', 'minecraft:parrot_spawn_egg', 'minecraft:turtle_spawn_egg', 'minecraft:cat_spawn_egg', 'mowziesmobs:sculptor_spawn_egg', 'minecraft:vindicator_spawn_egg', 'minecraft:trader_llama_spawn_egg', 'minecraft:salmon_spawn_egg', 'minecraft:warden_spawn_egg', 'minecraft:vex_spawn_egg', 'irons_spellbooks:ice_spider_spawn_egg', 'minecraft:frog_spawn_egg', 'minecraft:witch_spawn_egg', 'minecraft:dolphin_spawn_egg', 'minecraft:pillager_spawn_egg', 'minecraft:wandering_trader_spawn_egg', 'minecraft:magma_cube_spawn_egg', 'artifacts:mimic_spawn_egg', 'minecraft:panda_spawn_egg', 'minecraft:axolotl_spawn_egg', 'minecraft:breeze_spawn_egg', 'minecraft:tropical_fish_spawn_egg', 'mowziesmobs:umvuthana_raptor_spawn_egg', 'minecraft:hoglin_spawn_egg', 'minecraft:armadillo_spawn_egg', 'minecraft:donkey_spawn_egg', 'dried_ghast:ghastling_spawn_egg', 'minecraft:llama_spawn_egg', 'mowziesmobs:naga_spawn_egg', 'minecraft:polar_bear_spawn_egg', 'minecraft:bogged_spawn_egg', 'minecraft:zombie_horse_spawn_egg', 'mowziesmobs:grottol_spawn_egg', 'dried_ghast:happy_ghast_spawn_egg', 'minecraft:silverfish_spawn_egg', 'minecraft:piglin_spawn_egg', 'minecraft:zombified_piglin_spawn_egg', 'minecraft:drowned_spawn_egg', 'minecraft:zombie_villager_spawn_egg', 'minecraft:bat_spawn_egg', 'minecraft:mooshroom_spawn_egg', 'minecraft:cave_spider_spawn_egg', 'minecraft:allay_spawn_egg', 'mowziesmobs:umvuthi_spawn_egg', 'mowziesmobs:foliaath_spawn_egg', 'minecraft:zoglin_spawn_egg', 'minecraft:pufferfish_spawn_egg', 'minecraft:spider_spawn_egg', 'irons_spellbooks:archevoker_spawn_egg', 'minecraft:mule_spawn_egg', 'minecraft:horse_spawn_egg', 'minecraft:piglin_brute_spawn_egg', 'minecraft:ocelot_spawn_egg', 'mowziesmobs:frostmaw_spawn_egg', 'minecraft:skeleton_horse_spawn_egg', 'minecraft:guardian_spawn_egg', 'irons_spellbooks:pyromancer_spawn_egg', 'irons_spellbooks:keeper_spawn_egg', 'mowziesmobs:lantern_spawn_egg', 'minecraft:pig_spawn_egg', 'minecraft:phantom_spawn_egg', 'irons_spellbooks:cryomancer_spawn_egg', 'minecraft:squid_spawn_egg', 'minecraft:blaze_spawn_egg', 'minecraft:ghast_spawn_egg', 'minecraft:evoker_spawn_egg', 'minecraft:fox_spawn_egg', 'minecraft:endermite_spawn_egg']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:budding_amethyst matches with ['minecraft:budding_amethyst']
DEBUG - Propagation - _filterAtomicInputs - Keyword *:infested_* matches with ['minecraft:infested_cobblestone', 'betterarcheology:infested_mud_bricks']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:structure* matches with ['minecraft:structure_void', 'minecraft:structure_block']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:farmland matches with ['minecraft:farmland']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:reinforced_deepslate matches with ['minecraft:reinforced_deepslate']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:jigsaw matches with ['minecraft:jigsaw']
DEBUG - Propagation - _filterAtomicInputs - Keyword *debug_* matches with ['minecraft:debug_stick', 'sophisticatedstorage:debug_tool']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:dirt_path matches with []
DEBUG - Propagation - _filterAtomicInputs - Keyword create:minecart_contraption matches with ['create:minecart_contraption']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:petrified_oak_slab matches with ['minecraft:petrified_oak_slab']
DEBUG - Propagation - _filterAtomicInputs - Keyword *command_block* matches with ['minecraft:chain_command_block', 'minecraft:repeating_command_block', 'minecraft:command_block_minecart', 'minecraft:command_block']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:knowledge_book matches with ['minecraft:knowledge_book']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:bedrock matches with ['minecraft:bedrock']
DEBUG - Propagation - _filterAtomicInputs - Keyword minecraft:barrier matches with ['minecraft:barrier']
INFO - Propagation - _filterAtomicInputs - Dropped 134 nodes
INFO - Propagation - generateAtomicInputs - Full input table size is 966

In [4]:
prop.saveAtomicInputs()

INFO - Propagation - saveAtomicInputs - Inputs saved to atomicInputs.csv

# Setting values

In [10]:
display(prop.inputs)

def remaining():
    done = len(prop.inputs[prop.inputs['value'] != 0])
    total = len(prop.inputs)
    N = 50

    print(f"{int(done/total*N)*'■'}{(N-int(done/total*N))*'□'} {done}/{total}")

,node,value,cycle,representative,partition
0,create:rare_simi_package,0,None,None,part-001
1,protection_pixel:hellsnakeas_chestplate,0,None,None,part-002
2,minecraft:basalt,0,None,None,part-003
3,supplementaries:suspicious_gravel_bricks,0,None,None,part-004
5,minecraft:nether_gold_ore,0,None,None,part-000
...,...,...,...,...,...
1095,cycle-229,0,"{create:experience_nugget, create:experience_b...",None,part-1107
1096,cycle-231,0,"{supplementaries:feather_block, minecraft:feat...",None,part-000
1097,cycle-233,0,"{minecraft:raw_gold, minecraft:raw_gold_block}",None,part-000
1098,cycle-234,0,"{minecraft:hay_block, minecraft:wheat}",None,part-000
1099,cycle-235,0,"{create:raw_zinc_block, create:raw_zinc}",None,part-000

In [11]:
prop.matchInputValue("*_log", 20, overwrite=True)
prop.matchInputValue("betterarcheology:rotten_log", 30, overwrite=True)
display(prop.inputs)
remaining()

INFO - Propagation - matchInputValue - *_log matches up with {'minecraft:birch_log', 'palegarden:pale_log', 'minecraft:oak_log', 'minecraft:jungle_log', 'minecraft:spruce_log', 'betterarcheology:rotten_log', 'minecraft:cherry_log', 'minecraft:acacia_log', 'minecraft:dark_oak_log', 'mowziesmobs:clawed_log', 'minecraft:mangrove_log'}
INFO - Propagation - matchInputValue - betterarcheology:rotten_log matches up with {'betterarcheology:rotten_log'}

,node,value,cycle,representative,partition
0,create:rare_simi_package,0,None,None,part-001
1,protection_pixel:hellsnakeas_chestplate,0,None,None,part-002
2,minecraft:basalt,0,None,None,part-003
3,supplementaries:suspicious_gravel_bricks,0,None,None,part-004
5,minecraft:nether_gold_ore,0,None,None,part-000
...,...,...,...,...,...
1095,cycle-229,0,"{create:experience_nugget, create:experience_b...",None,part-1107
1096,cycle-231,0,"{supplementaries:feather_block, minecraft:feat...",None,part-000
1097,cycle-233,0,"{minecraft:raw_gold, minecraft:raw_gold_block}",None,part-000
1098,cycle-234,0,"{minecraft:hay_block, minecraft:wheat}",None,part-000
1099,cycle-235,0,"{create:raw_zinc_block, create:raw_zinc}",None,part-000

□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□ 11/966

In [13]:
prop.matchInputValue("*_leaves", 1, overwrite=True)
display(prop.inputs)
remaining()

INFO - Propagation - matchInputValue - *_leaves matches up with {'minecraft:flowering_azalea_leaves', 'minecraft:cherry_leaves', 'minecraft:oak_leaves', 'minecraft:jungle_leaves', 'minecraft:azalea_leaves', 'minecraft:birch_leaves', 'palegarden:pale_leaves', 'minecraft:acacia_leaves', 'minecraft:mangrove_leaves', 'minecraft:dark_oak_leaves', 'minecraft:spruce_leaves'}

,node,value,cycle,representative,partition
0,create:rare_simi_package,0,None,None,part-001
1,protection_pixel:hellsnakeas_chestplate,0,None,None,part-002
2,minecraft:basalt,0,None,None,part-003
3,supplementaries:suspicious_gravel_bricks,0,None,None,part-004
5,minecraft:nether_gold_ore,0,None,None,part-000
...,...,...,...,...,...
1095,cycle-229,0,"{create:experience_nugget, create:experience_b...",None,part-1107
1096,cycle-231,0,"{supplementaries:feather_block, minecraft:feat...",None,part-000
1097,cycle-233,0,"{minecraft:raw_gold, minecraft:raw_gold_block}",None,part-000
1098,cycle-234,0,"{minecraft:hay_block, minecraft:wheat}",None,part-000
1099,cycle-235,0,"{create:raw_zinc_block, create:raw_zinc}",None,part-000

■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□ 22/966

In [16]:
prop.matchInputValue("*_sapling", 5, overwrite=True)
display(prop.inputs)
remaining()

INFO - Propagation - matchInputValue - *_sapling matches up with {'minecraft:acacia_sapling', 'minecraft:birch_sapling', 'minecraft:jungle_sapling', 'minecraft:spruce_sapling', 'minecraft:dark_oak_sapling', 'minecraft:oak_sapling', 'minecraft:cherry_sapling'}

,node,value,cycle,representative,partition
0,create:rare_simi_package,0,None,None,part-001
1,protection_pixel:hellsnakeas_chestplate,0,None,None,part-002
2,minecraft:basalt,0,None,None,part-003
3,supplementaries:suspicious_gravel_bricks,0,None,None,part-004
5,minecraft:nether_gold_ore,0,None,None,part-000
...,...,...,...,...,...
1095,cycle-229,0,"{create:experience_nugget, create:experience_b...",None,part-1107
1096,cycle-231,0,"{supplementaries:feather_block, minecraft:feat...",None,part-000
1097,cycle-233,0,"{minecraft:raw_gold, minecraft:raw_gold_block}",None,part-000
1098,cycle-234,0,"{minecraft:hay_block, minecraft:wheat}",None,part-000
1099,cycle-235,0,"{create:raw_zinc_block, create:raw_zinc}",None,part-000

■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□ 29/966

In [19]:
prop.saveAtomicInputs()

INFO - Propagation - saveAtomicInputs - Inputs saved to atomicInputs.csv

# Solve

In [4]:
prop.loadAtomicInputs()
prop.setupForSolving()
prop.solve()

INFO - Propagation - loadAtomicInputs - Found an existing input file

TypeError: 'NodeView' object does not support item assignment

In [ ]:
output = prop.getOutputs()
print(output.to_markdown())
output.to_json("SCT_Table.json")